### PR TITLE
Increases constrast of links and uses underline as secondary visual cue

### PR DESCRIPTION
**Pull request by scottmries**
Minimum contrast between text links and background color is 4.5:1 for small text in WCAG2.1AA, as required by [Success Criterion 1.4.3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html). This addresses this issue on both the "sign up" and "forgot password" links, in their focused, hovered, and normal states.

Providing links with underlines ensures that they are visually evident without color vision, addressing failure [F73](https://www.w3.org/TR/2008/WD-WCAG20-TECHS-20081103/F73).

### CODE REVIEW

**Comment by wmorrell** [comment]
I'll need to take some time to try this out. I believe there are a few places where `<A>` tags are being used, but not as links with an `HREF` attribute. This switch may add a bunch of underlines in unexpected places. The change is correct, but those incorrect uses of `<A>` should get fixed in tandem.

**Comment by wmorrell** [comment]
Further fixing this is going to require a lot more effort. As-is, this adds underlines in at least four places where I believe the underline decoration is not appropriate:
1. On the close control of dismissible alerts using an `<A>` instead of `<BUTTON>`; should switch to use `<BUTTON>`.
2. On the pill navigation tabs of Study pages; the pill should be sufficient secondary visual cue.
3. In Bootstrap label elements used as mini-buttons in alerts (e.g. alert indicating table is dropzone target in Study Description view); an alternative way to indicate these should be considered, they are labels now because having the links be normal text (even with underline) was seen as not prominent enough. Maybe make full buttons.
4. In dropdown/dropup button menu items.

**Review by jim — APPROVED** [review]
I think this is a good default. We can address the instances of links-not-as-links that @wmorrell listed.

**Comment by scottmries** [comment]
I excluded the instances of `a` tags @wmorrell mentioned.

**Comment by wmorrell** [comment]
Closing this, the underlying issue should now be solved in the updated page using Bootstrap 5.

**Pull request closed without merging**
